[project]
name = "srcup"
version = "0.4.17"
description = ""
readme = "README.md"
requires-python = ">=3.10,<4"
authors = [
    { name = "Tony Rocco Valentine", email = "tvalentine@dedaub.com" },
    { name = "Ilias Tsatiris", email = "ilias@dedaub.com" },
]
dependencies = [
    "aiohttp>=3.8.5,<4",
    "crytic-compile",
    "eth-hash[pycryptodome]>=0.8.0,<1.0",
    "packaging>=24,<26",
    "pydantic>=2.5.3,<3",
    "python-dotenv>=1.2.0,<2",
    "typer[all]>=0.25.0,<0.26",
]

[project.scripts]
srcup = "srcup.__main__:main"

[dependency-groups]
dev = [
    "mypy>=0.991,<1",
]

[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["srcup"]

[tool.uv.sources]
crytic-compile = { git = "https://github.com/Dedaub/crytic-compile.git", branch = "master" }


[tool.pyright]
venvPath = "."
venv = ".venv"
